// ─── Realtime event kinds ─────────────────────────────────────────────────────

export type RealtimeEventKind =
  | 'duel.accepted'
  | 'duel.expired'
  | 'verification.started'
  | 'verification.completed'
  | 'reward.paid'
  | 'tournament.started'
  | 'tournament.match_ready'
  | 'tournament.match_completed'
  | 'tournament.completed'

// ─── Base event ───────────────────────────────────────────────────────────────

export interface BaseEvent {
  /** UUID generated by the publisher. */
  id: string
  kind: RealtimeEventKind
  occurredAt: string // ISO timestamp
  /**
   * When set, only stream to the client whose userId matches.
   * When omitted, broadcast to every connected client.
   */
  targetUserId?: string
}

// ─── Typed event shapes ───────────────────────────────────────────────────────

export interface DuelAcceptedEvent extends BaseEvent {
  kind: 'duel.accepted'
  duelId: string
  creatorTag: string
  challengerTag: string
  gameId: string
  stakeSol: number
}

export interface DuelExpiredEvent extends BaseEvent {
  kind: 'duel.expired'
  duelId: string
  creatorTag: string
  challengerTag: string | null
  refundedSol: number
}

export interface VerificationStartedEvent extends BaseEvent {
  kind: 'verification.started'
  duelId: string
  gameId: string
  player1Tag: string
  player2Tag: string
}

export interface VerificationCompletedEvent extends BaseEvent {
  kind: 'verification.completed'
  duelId: string
  winnerTag: string | null
  status: 'verified' | 'disputed' | 'timeout'
  battleTime: string | null
}

export interface RewardPaidEvent extends BaseEvent {
  kind: 'reward.paid'
  duelId: string
  winnerTag: string
  amountSol: number
  feeSol: number
}

export interface TournamentStartedEvent extends BaseEvent {
  kind: 'tournament.started'
  tournamentId: string
  name: string
  playerCount: number
}

export interface TournamentMatchReadyEvent extends BaseEvent {
  kind: 'tournament.match_ready'
  tournamentId: string
  matchId: string
  player1Tag: string
  player2Tag: string
  roundNumber: number
}

export interface TournamentMatchCompletedEvent extends BaseEvent {
  kind: 'tournament.match_completed'
  tournamentId: string
  matchId: string
  winnerTag: string
  roundNumber: number
}

export interface TournamentCompletedEvent extends BaseEvent {
  kind: 'tournament.completed'
  tournamentId: string
  name: string
  winnerTag: string
  prizePoolSol: number
}

// ─── Union ────────────────────────────────────────────────────────────────────

export type RealtimeEvent =
  | DuelAcceptedEvent
  | DuelExpiredEvent
  | VerificationStartedEvent
  | VerificationCompletedEvent
  | RewardPaidEvent
  | TournamentStartedEvent
  | TournamentMatchReadyEvent
  | TournamentMatchCompletedEvent
  | TournamentCompletedEvent

/** Map from kind → concrete event type, used for type-safe subscriptions. */
export type EventMap = {
  [K in RealtimeEventKind]: Extract<RealtimeEvent, { kind: K }>
}

/** Internal ping sent by SSEManager heartbeat — not a RealtimeEvent. */
export interface PingEvent {
  kind: 'ping'
}
