// ─── Realtime event kinds ─────────────────────────────────────────────────────

export type RealtimeEventKind =
  | 'duel.accepted'
  | 'duel.expired'
  | 'verification.started'
  | 'verification.completed'
  | 'reward.paid'
  | 'dispute.raised'
  | 'dispute.resolved'
  | 'tournament.started'
  | 'tournament.match_ready'
  | 'tournament.match_completed'
  | 'tournament.completed'
  | 'withdrawal.held'
  | 'withdrawal.approved'
  | 'withdrawal.rejected'
  | 'withdrawal.completed'
  | 'withdrawal.failed'
  | 'deposit.credited'

// ─── Base event ───────────────────────────────────────────────────────────────

export interface BaseEvent {
  /** UUID generated by the publisher. */
  id: string
  kind: RealtimeEventKind
  occurredAt: string // ISO timestamp
  /**
   * When set, only stream to the client whose userId matches.
   * When omitted, broadcast to every connected client.
   */
  targetUserId?: string
}

// ─── Typed event shapes ───────────────────────────────────────────────────────

export interface DuelAcceptedEvent extends BaseEvent {
  kind: 'duel.accepted'
  duelId: string
  creatorTag: string
  challengerTag: string
  gameId: string
  stakeSol: number
}

export interface DuelExpiredEvent extends BaseEvent {
  kind: 'duel.expired'
  duelId: string
  creatorTag: string
  challengerTag: string | null
  refundedSol: number
}

export interface VerificationStartedEvent extends BaseEvent {
  kind: 'verification.started'
  duelId: string
  gameId: string
  player1Tag: string
  player2Tag: string
}

export interface VerificationCompletedEvent extends BaseEvent {
  kind: 'verification.completed'
  duelId: string
  winnerTag: string | null
  status: 'verified' | 'disputed' | 'timeout' | 'refunded'
  battleTime: string | null
}

export interface RewardPaidEvent extends BaseEvent {
  kind: 'reward.paid'
  duelId: string
  winnerTag: string
  amountSol: number
  feeSol: number
}

export interface TournamentStartedEvent extends BaseEvent {
  kind: 'tournament.started'
  tournamentId: string
  name: string
  playerCount: number
}

export interface TournamentMatchReadyEvent extends BaseEvent {
  kind: 'tournament.match_ready'
  tournamentId: string
  matchId: string
  player1Tag: string
  player2Tag: string
  roundNumber: number
}

export interface TournamentMatchCompletedEvent extends BaseEvent {
  kind: 'tournament.match_completed'
  tournamentId: string
  matchId: string
  winnerTag: string
  roundNumber: number
}

export interface TournamentCompletedEvent extends BaseEvent {
  kind: 'tournament.completed'
  tournamentId: string
  name: string
  winnerTag: string
  prizePoolSol: number
}

export interface DisputeRaisedEvent extends BaseEvent {
  kind: 'dispute.raised'
  duelId: string
  /** Username of the player who raised it; null when system-raised. */
  raisedByTag: string | null
  /** True when the duel had already settled (result under review, not frozen funds). */
  postSettlement: boolean
}

export interface DisputeResolvedEvent extends BaseEvent {
  kind: 'dispute.resolved'
  duelId: string
  /** Final dispute status: RESOLVED_CREATOR_WIN | RESOLVED_OPPONENT_WIN | RESOLVED_REFUND | REJECTED */
  resolution: string
  /** Username of the standing winner after resolution; null when refunded/voided. */
  winnerTag: string | null
}

// ─── Credits: money entering and leaving the platform ────────────────────────
//
// Every event below MUST carry `targetUserId`. These describe one person's
// money; an untargeted publish broadcasts it to every connected client.

/** Withdrawal parked for manual review (an active dispute blocks auto-approval). */
export interface WithdrawalHeldEvent extends BaseEvent {
  kind: 'withdrawal.held'
  withdrawalId: string
  amountSol: number
  /** Why it was held, e.g. the open dispute blocking it. */
  reason: string | null
}

export interface WithdrawalApprovedEvent extends BaseEvent {
  kind: 'withdrawal.approved'
  withdrawalId: string
  amountSol: number
}

export interface WithdrawalRejectedEvent extends BaseEvent {
  kind: 'withdrawal.rejected'
  withdrawalId: string
  amountSol: number
  /** Admin's review note, surfaced verbatim. A rejection with no stated reason
   *  is worse than no notification, so this is deliberately user-visible. */
  reason: string | null
}

export interface WithdrawalCompletedEvent extends BaseEvent {
  kind: 'withdrawal.completed'
  withdrawalId: string
  /** What actually landed on-chain, net of the withdrawal fee. */
  netSol: number
  feeSol: number
  /** On-chain signature so the user can verify the payout independently. */
  txSignature: string
}

export interface WithdrawalFailedEvent extends BaseEvent {
  kind: 'withdrawal.failed'
  withdrawalId: string
  amountSol: number
}

export interface DepositCreditedEvent extends BaseEvent {
  kind: 'deposit.credited'
  depositId: string
  creditedSol: number
  feeSol: number
  txSignature: string
}

// ─── Union ────────────────────────────────────────────────────────────────────

export type RealtimeEvent =
  | DuelAcceptedEvent
  | DuelExpiredEvent
  | VerificationStartedEvent
  | VerificationCompletedEvent
  | RewardPaidEvent
  | DisputeRaisedEvent
  | DisputeResolvedEvent
  | TournamentStartedEvent
  | TournamentMatchReadyEvent
  | TournamentMatchCompletedEvent
  | TournamentCompletedEvent
  | WithdrawalHeldEvent
  | WithdrawalApprovedEvent
  | WithdrawalRejectedEvent
  | WithdrawalCompletedEvent
  | WithdrawalFailedEvent
  | DepositCreditedEvent

/** Map from kind → concrete event type, used for type-safe subscriptions. */
export type EventMap = {
  [K in RealtimeEventKind]: Extract<RealtimeEvent, { kind: K }>
}

/** Internal ping sent by SSEManager heartbeat — not a RealtimeEvent. */
export interface PingEvent {
  kind: 'ping'
}
